services:
  - type: web
    name: signature-app
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install --upgrade pip setuptools==65.5.0 wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
